name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'
          cache: 'npm'
          cache-dependency-path: planner/package-lock.json


      - name: Install dependencies
        working-directory: planner
        run: npm ci

      - name: Build
        working-directory: planner
        run: npm run build -- --base-href=/planner/
        # Replace 'planner' with your repository name

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: planner/dist/planner/browser # Angular 17 output directory
          branch: gh-pages